version: '3'

services:
  alfred-dashboard:
    build: .
    container_name: alfred-dashboard
    ports:
      - "8050:8050"
    volumes:
      - ./config:/app/config
    environment:
      - DASH_DEBUG=true
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python app.py
